version=${project.version}
buildtime=${timestamp}
builder=${env.USERNAME}
builderName=${temps.build.user.name}
builderEmail=${temps.build.user.email}
buildhost=${env.COMPUTERNAME}
buildOs=${os.name}
gitBranch=${temps.branch}
gitCommitIdDescribe=${temps.commit.id.describe}
gitCommitId=${temps.commit.id.full}
gitCommitUrl=${temps.remote.origin.url}
gitCommitTime=${temps.commit.time}
gitDirty=${temps.dirty}